<?php

namespace Database\Seeders;

use App\Models\MataKuliah;
use Illuminate\Database\Seeder;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // kurikulum 2025===============================================================================================================================
        $matkul = [
            [
                'nama_matkul' => 'Agama',
                'kode_mk' => 'TIF410801',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Pancasila',
                'kode_mk' => 'TIF410802',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Basic English',
                'kode_mk' => 'TIF410803',
                'sks_teori' => '1',
                'sks_praktek' => '1',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Logika dan Algoritma',
                'kode_mk' => 'TIF410804',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Interaksi Manusia dan Komputer',
                'kode_mk' => 'TIF410805',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],            [
                'nama_matkul' => 'Pemrograman Dasar',
                'kode_mk' => 'TIF410806',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop A',
                'kode_mk' => 'TIF410807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop B',
                'kode_mk' => 'TIF410807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop C',
                'kode_mk' => 'TIF410807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data A',
                'kode_mk' => 'TIF410808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data B',
                'kode_mk' => 'TIF410808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data C',
                'kode_mk' => 'TIF410808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '1',                
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Bahasa Indonesia',
                'kode_mk' => 'TIF420801',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Kewarganegaraan',
                'kode_mk' => 'TIF420802',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Intermediate English',
                'kode_mk' => 'TIF420803',
                'sks_teori' => '1',
                'sks_praktek' => '1',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Sistem Operasi',
                'kode_mk' => 'TIF420804',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Konsep Dasar Jaringan',
                'kode_mk' => 'TIF420805',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Perencanaan  Perangkat Lunak',
                'kode_mk' => 'TIF420806',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web 1 A',
                'kode_mk' => 'TIF420807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web 1 B',
                'kode_mk' => 'TIF420807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web 1 C',
                'kode_mk' => 'TIF420807',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Rekayasa Perangkat Lunak A',
                'kode_mk' => 'TIF420808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Rekayasa Perangkat Lunak B',
                'kode_mk' => 'TIF420808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Rekayasa Perangkat Lunak C',
                'kode_mk' => 'TIF420808',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            // kurikulum 2021==========================================================================================================================
            [
                'nama_matkul' => 'Interpersonal Skill',
                'kode_mk' => 'TIF430701',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Matematika Diskrit',
                'kode_mk' => 'TIF430702',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Konsep Jaringan Komputer',
                'kode_mk' => 'TIF430703',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Struktur Data',
                'kode_mk' => 'TIF430704',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Kualitas Perangkat Lunak A',
                'kode_mk' => 'TIF430705',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Kualitas Perangkat Lunak B',
                'kode_mk' => 'TIF430705',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web A',
                'kode_mk' => 'TIF430706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web B',
                'kode_mk' => 'TIF430706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Mobile Applications A',
                'kode_mk' => 'TIF430707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Mobile Applications B',
                'kode_mk' => 'TIF430707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Literasi Digital',
                'kode_mk' => 'TIF440701',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Kewirausahaan',
                'kode_mk' => 'TIF440702',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Manajemen Kualitas Perangkat Lunak',
                'kode_mk' => 'TIF440703',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Perawatan Perangkat Lunak',
                'kode_mk' => 'TIF440704',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Pengujian Perangkat Lunak',
                'kode_mk' => 'TIF440705',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Web Framework A',
                'kode_mk' => 'TIF440706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Web Framework B',
                'kode_mk' => 'TIF440706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Mobile Applications Framework A',
                'kode_mk' => 'TIF440707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Mobile Applications Framework B',
                'kode_mk' => 'TIF440707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Aplikasi Sistem Tertanam',
                'kode_mk' => 'TIF450701',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Sistem Cerdas',
                'kode_mk' => 'TIF450702',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            // [
            //     'nama_matkul' => 'Agroinformatika',
            //     'kode_mk' => '',
            //     'sks_teori' => '',
            //     'sks_praktek' => '',
            //     'semester' => '5',
            //     'status' => 'Inactive',
            //     'created_at' => now(),
            // ],
            [
                'nama_matkul' => 'Sistem Informasi Enterprise',
                'kode_mk' => 'TIF450703',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Multimedia Permainan',
                'kode_mk' => 'TIF450704',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengolahan Citra dan Vision A',
                'kode_mk' => 'TIF450705',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengolahan Citra dan Vision B',
                'kode_mk' => 'TIF450705',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Tertanam A',
                'kode_mk' => 'TIF450706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Tertanam B',
                'kode_mk' => 'TIF450706',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Cerdas A',
                'kode_mk' => 'TIF450707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Cerdas B',
                'kode_mk' => 'TIF450707',
                'sks_teori' => '0',
                'sks_praktek' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Teknik Penulisan Ilmiah',
                'kode_mk' => 'TIF460701',
                'sks_teori' => '2',
                'sks_praktek' => '0',
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Statistika',
                'kode_mk' => 'TIF460702',
                'sks_teori' => '2',
                'sks_praktek' => '0',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Tren Teknologi',
                'kode_mk' => 'TIF460703',
                'sks_teori' => '2',
                'sks_praktek' => '0',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Data Warehouse',
                'kode_mk' => 'TIF460704',
                'sks_teori' => '2',
                'sks_praktek' => '0',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Developer Operational',
                'kode_mk' => 'TIF460705',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Developer Operational B',
                'kode_mk' => 'TIF460705',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Inactive',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Tata Kelola Teknologi Informasi',
                'kode_mk' => 'TIF460706',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Tata Kelola Teknologi Informasi B',
                'kode_mk' => 'TIF460706',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Inactive',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Proyek Sistem Informasi',
                'kode_mk' => 'TIF460707',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Proyek Sistem Informasi B',
                'kode_mk' => 'TIF460707',
                'sks_teori' => '0',
                'sks_praktek' => '4',   
                'semester' => '6',
                'status' => 'Inactive',
                'created_at' => now(),
            ],
        ];

        foreach ($matkul as $matkul) {
            MataKuliah::create($matkul);
        }
    }
}
