<?php

namespace Database\Seeders;

use App\Models\MataKuliah;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $matkul = [
            [
                'nama_matkul' => 'Agama',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Pancasila',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Basic English',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Logika dan Algoritma',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Konsep Basis Data',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],            [
                'nama_matkul' => 'Pemrograman Dasar',
                'sks' => '2',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengembangan Perangkat Lunak A',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengembangan Perangkat Lunak B',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengembangan Perangkat Lunak C',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data A',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data B',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Basis Data C',
                'sks' => '4',
                'semester' => '1',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Bahasa Indonesia',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Intermediate English',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Interaksi Manusia dan Komputer',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Sistem Aplikasi Berbasis Obyek',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Perencanaan Proyek Perangkat lunak',
                'sks' => '2',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop A',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop B',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Desktop C',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Manajemen Proyek A',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Manajemen Proyek B',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Manajemen Proyek C',
                'sks' => '4',
                'semester' => '2',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Interpersonal Skill',
                'sks' => '2',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Matematika Diskrit',
                'sks' => '2',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Konsep Jaringan Komputer',
                'sks' => '2',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Struktur Data',
                'sks' => '2',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Kualitas Perangkat Lunak A',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Kualitas Perangkat Lunak B',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web A',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Berbasis Web B',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Mobile Applications A',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Mobile Applications B',
                'sks' => '4',
                'semester' => '3',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Literasi Digital',
                'sks' => '2',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Kewirausahaan',
                'sks' => '2',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Manajemen Kualitas Perangkat Lunak',
                'sks' => '2',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Perawatan Perangkat Lunak',
                'sks' => '2',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Pengujian Perangkat Lunak',
                'sks' => '2',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Web Framework A',
                'sks' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Informasi Web Framework B',
                'sks' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Mobile Applications Framework A',
                'sks' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Mobile Applications Framework B',
                'sks' => '4',
                'semester' => '4',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Aplikasi Sistem Tertanam',
                'sks' => '2',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Sistem Cerdas',
                'sks' => '2',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Agroinformatika',
                'sks' => '2',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Sistem Informasi Enterprise',
                'sks' => '2',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Multimedia Permainan',
                'sks' => '2',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengolahan Citra dan Vision A',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Pengolahan Citra dan Vision B',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Tertanam A',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Tertanam B',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Cerdas A',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Sistem Cerdas B',
                'sks' => '4',
                'semester' => '5',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Teknik Penulisan Ilmiah',
                'sks' => '2',
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Statistika',
                'sks' => '2',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Tren Teknologi',
                'sks' => '2',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Data Warehouse',
                'sks' => '2',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Developer Operational A',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Developer Operational B',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Tata Kelola Teknologi Informasi A',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Tata Kelola Teknologi Informasi B',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Proyek Sistem Informasi A',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
            [
                'nama_matkul' => 'Workshop Proyek Sistem Informasi B',
                'sks' => '4',   
                'semester' => '6',
                'status' => 'Active',
                'created_at' => now(),
            ],
        ];

        foreach ($matkul as $matkul) {
            MataKuliah::create($matkul);
        }
    }
}
